
README.org ---  description



Copyright (C) 2009-2012 Roman V. Prikhodchenko



Author: Roman V. Prikhodchenko <chujoii@gmail.com>

  

  This file is part of segment-display.
  
  segment-display is free software: you can redistribute it and/or modify
  it under the terms of the GNU General Public License as published by
  the Free Software Foundation, either version 3 of the License, or
  (at your option) any later version.
  
  segment-display is distributed in the hope that it will be useful,
  but WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
  GNU General Public License for more details.
  
  You should have received a copy of the GNU General Public License
  along with segment-display.  If not, see <http://www.gnu.org/licenses/>.
  
  
  
* Keywords:
  seven segment display rc shift
  

* Description:
  seven segment display rc shift
  
  
* Usage:
  
  read with emacs (3__3) org mode
  
  
  
  
* History:
  
  initial project version began about 2009.10(Oct).20.
  
* Dependences:
  


  
  
  
